[package]
name = "example"
version.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_variants = { path = ".." }